# SITE CONFIGURATION
title: A Website # your site title
author: GitHub User # You :P
description: > # Meta description of Homepage
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/WEDesignWebsite" # the subpath of your site, e.g. /blog
url: "https://Sciencesing.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: WE Design
  links:
    - https://www.instagram.com/windenergydesign
    - https://www.facebook.com/windenergydesign
    - https://ca.linkedin.com/company/windenergydesign
    - #https://plus.google.com/+windenergydesign
    - #https://github.com/benbalter
    - #https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Beta', link: '/beta'}
  - {name: 'Important Dates', link: '/importantdates'}
  - {name: 'Join Us', link: '/joinus'}

tagline: >
  University of Manitoba's small scale wind turbine design team

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: contact@windenergydesign.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: WE Design # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: WE Design # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
