# SITE CONFIGURATION
title: WE Design # your site title
author: Wind Energy Design # You :P
description: > # Meta description of Homepage Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  
    Engineering student design team for small-scale wind turbines and green energy.
logo: 'assets/img/teamlogo.jpg'
favicon: 'assets/img/teamfaviconcircle.png'
baseurl: "" # the subpath of your site, e.g. /blog
# old one is: /WEDesignWebsite
url: "https://windenergydesign.com/" # the base hostname & protocol for your site, e.g. http://example.com
# old one is: sciencesing.github.io

# SEO PLUGIN

social:
  name: WE Design
  links:
    - https://www.instagram.com/windenergydesign
    - https://www.facebook.com/windenergydesign
    - https://ca.linkedin.com/company/windenergydesign
    - #https://plus.google.com/+windenergydesign
    - #https://github.com/benbalter
    - #https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About Us', link: '/aboutus'}
  - {name: 'Contact', link: '/contact'}
  - {name: 'Important Dates', link: '/importantdates'}
  - {name: 'Join Us', link: '/joinus'}
  - {name: 'Sponsors', link: '/sponsors'}

tagline: >
  University of Manitoba's small scale wind turbine design team
hero_img: posts/Homepage_Turbines_Light_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: contact@windenergydesign.com # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
#github_username:  janczizikow # replace with your_github_username or comment to remove link from footer
instagram_username: windenergydesign # replace with your_instagram_username or comment to remove link from footer
linkedin_username: windenergydesign
facebook_username: windenergydesign

disqus:
  shortname: windenergydesign # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
#  - vendor
  - npm-debug.log
 # - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
